version: '3.8'

services:
  db:
    container_name: postgres-ecomet
    image: postgres:14
    restart: on-failure
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data/

  api:
    container_name: api-ecomet
    build: ./api
    env_file:
      - ./.env
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - db
    command: uvicorn main:app --reload --host 0.0.0.0

  scrapy:
    container_name: scrapy-ecomet
    build: ./scrapy
    env_file:
      - ./.env
    volumes:
      - ./scrapy:/scrapy
    ports:
      - 8001:8001
    restart: on-failure
    depends_on:
      - db
      - api
