"""add coord

Revision ID: 92c50836dd73
Revises: 8cfe562fee61
Create Date: 2023-01-18 19:09:59.498773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c50836dd73'
down_revision = '8cfe562fee61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('cities', sa.Column('lon', sa.Float(), nullable=False))
    op.create_index(op.f('ix_cities_lat'), 'cities', ['lat'], unique=True)
    op.create_index(op.f('ix_cities_lon'), 'cities', ['lon'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_lon'), table_name='cities')
    op.drop_index(op.f('ix_cities_lat'), table_name='cities')
    op.drop_column('cities', 'lon')
    op.drop_column('cities', 'lat')
    # ### end Alembic commands ###
