"""datetime 

Revision ID: c498a7400157
Revises: 92c50836dd73
Create Date: 2023-01-18 21:23:07.787463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c498a7400157'
down_revision = '92c50836dd73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_weathers', sa.Column('datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city_weathers', 'datetime')
    # ### end Alembic commands ###
