"""presure, wind speed

Revision ID: cf0a43f8165a
Revises: c498a7400157
Create Date: 2023-01-18 21:30:12.379408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf0a43f8165a'
down_revision = 'c498a7400157'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_weathers', sa.Column('temperature', sa.Integer(), nullable=False))
    op.add_column('city_weathers', sa.Column('pressure', sa.Integer(), nullable=False))
    op.add_column('city_weathers', sa.Column('wind_speed', sa.Float(), nullable=False))
    op.alter_column('city_weathers', 'datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('city_weathers', 'weather')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_weathers', sa.Column('weather', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('city_weathers', 'datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('city_weathers', 'wind_speed')
    op.drop_column('city_weathers', 'pressure')
    op.drop_column('city_weathers', 'temperature')
    # ### end Alembic commands ###
